---
version: "3.7"

services:
  grpc-server:
    build: ./server
    image: node:16-alpine
    command: [ash, -c, "cd /usr/src/ && npm run monitor:container"]
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "4044:8080"
    networks:
      - leraning_grpc
    volumes:
      # - ./app:/usr/src/app/
      # - ./config:/usr/src/config/
      # - ./node_modules:/usr/src/node_modules/
      # - ./.env.container:/usr/src/.env.container
      - ./.env:/usr/src/.env
      - ./package.json:/usr/src/package.json
      # - ./package-lock.json:/usr/src/package-lock.json

networks:
  leraning_grpc:
