---
version: "3.7"

services:
  grpc_server:
    build: ./
    image: node:18-alpine
    command: [ash, -c, "cd /usr/src/ && npm install && npm run monitor:container"]
    environment:
      - TZ=America/Sao_Paulo
    # ports:
    #   - "4044:50051"
    networks:
      - learning_grpc
    restart: always
    volumes:
      - ./containers/server/node_modules:/usr/src/node_modules/
      - ./repositories/server/app:/usr/src/app/
      # - ./config:/usr/src/config/
      # - ./.env.container:/usr/src/.env.container
      - ./repositories/server/.env:/usr/src/.env
      - ./repositories/server/package.json:/usr/src/package.json

  grpc_client:
    build: ./
    image: node:18-alpine
    command: [ash, -c, "cd /usr/src/ && npm install && npm run monitor:container"]
    environment:
      - TZ=America/Sao_Paulo
    # ports:
    #   - "4044:50051"
    networks:
      - learning_grpc
    restart: always
    volumes:
      - ./containers/client/node_modules:/usr/src/node_modules/
      - ./repositories/client/app:/usr/src/app/
      # - ./config:/usr/src/config/
      # - ./.env.container:/usr/src/.env.container
      - ./repositories/client/.env:/usr/src/.env
      - ./repositories/client/package.json:/usr/src/package.json
    depends_on:
      - grpc_server

networks:
  learning_grpc:
